# a common search space: [lora_r2activate_fn, lora_r4, lora_r8, lora_r16, lora_gelu_r2, lora_gelu_r4, lora_gelu_r8, lora_gelu_r16, lora_d_parts_r2, lora_d_parts_r4, lora_d_parts_r8, lora_d_parts_r16]
lora_r1:
  peft_type: lora
  r: 1
  lora_alpha: 2
  activate_fn: ~
  d_parts: 1
lora_r2:
  peft_type: lora
  r: 2
  lora_alpha: 4
  activate_fn: ~
  d_parts: 1
lora_r3:
  peft_type: lora
  r: 3
  lora_alpha: 6
  activate_fn: ~
  d_parts: 1
lora_r4:
  peft_type: lora
  r: 4
  lora_alpha: 8
  activate_fn: ~
  d_parts: 1
lora_r5:
  peft_type: lora
  r: 5
  lora_alpha: 10
  activate_fn: ~
  d_parts: 1
lora_r6:
  peft_type: lora
  r: 6
  lora_alpha: 6
  activate_fn: ~
  d_parts: 1
lora_r7:
  peft_type: lora
  r: 7
  lora_alpha: 7
  activate_fn: ~
  d_parts: 1
lora_r8:
  peft_type: lora
  r: 8
  lora_alpha: 16
  activate_fn: ~
  d_parts: 1
lora_r9:
  peft_type: lora
  r: 9
  lora_alpha: 18
  activate_fn: ~
  d_parts: 1
lora_r10:
  peft_type: lora
  r: 10
  lora_alpha: 20
  activate_fn: ~
  d_parts: 1
lora_r11:
  peft_type: lora
  r: 11
  lora_alpha: 22
  activate_fn: ~
  d_parts: 1
lora_r12:
  peft_type: lora
  r: 12
  lora_alpha: 24
  activate_fn: ~
  d_parts: 1